name: Zig Tests

on:
  push:
    branches:
      - main
      - development
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches:
      - main
      - development
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.build_mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Install Linux-only dependencies (Wayland etc.)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev libx11-dev libxrandr-dev libxi-dev \
            libxinerama-dev libxcursor-dev libwayland-dev \
            wayland-protocols wayland-scanner++

      - name: Run Zig tests
        run: |
          zig build test -Doptimize=${{ matrix.build_mode }}
