name: Zig Tests

on:
  push:
    paths:
      - '**.zig'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.zig'
      - '.github/workflows/ci.yml'

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.build_mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Zig version on Unix
        id: zigversion
        if: runner.os != 'Windows'
        run: |
          echo "version=$(cat .zigversion)" >> $GITHUB_OUTPUT

      - name: Read Zig version on Windows
        id: zigversion
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $zigversion = Get-Content .zigversion
          "version=$zigversion" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ steps.zigversion.outputs.version }}

      - name: Run Zig tests
        run: |
          zig build test -Doptimize=${{ matrix.build_mode }}
