name: Zig Tests

on:
  push:
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.build_mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0

      - name: Run Zig tests
        run: |
          zig build test -Doptimize=${{ matrix.build_mode }}
