name: Zig Tests

on:
  push:
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'

jobs:
  linux:
    name: Linux Zig Test / ${{ matrix.build_mode }}
    runs-on: [self-hosted, linux]
    timeout-minutes: 1
    continue-on-error: true
    strategy:
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}

  fallback-linux:
    name: Fallback Linux Test / ${{ matrix.build_mode }}
    needs: linux
    if: failure()
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}
      
  macos:
    name: MacOS Test / ${{ matrix.build_mode }}
    runs-on: macos-latest
    strategy:
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}

  windows:
    name: Windows Test / ${{ matrix.build_mode }}
    runs-on: windows-latest
    strategy:
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}
