name: Zig CI

on:
  push:
    branches:
      - main
      - development
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches:
      - main
      - development
    paths:
      - '**.zig'
      - '.github/workflows/ci.yaml'

jobs:
  determine-runner:
    name: Determine available runner
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.set-runner.outputs.runner }}
    steps:
      - uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        id: set-runner
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          min-available-runners: 1
          github-token: ${{ secrets.GHTOKEN_DETERMINERUNNER }}

  linux-test:
    name: Test Linux / ${{ matrix.build_mode }}
    needs: determine-runner
    runs-on: ${{ needs.determine-runner.outputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}

  mac-test:
    name: Test macOS / ${{ matrix.build_mode }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}

  windows-test:
    name: Test Windows / ${{ matrix.build_mode }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_mode: [Debug, ReleaseSafe, ReleaseFast, ReleaseSmall]
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.0
      - run: zig build test -DisCI=true -Doptimize=${{ matrix.build_mode }}
